name: generate-snake-game

on:
  schedule: # roda automaticamente todo dia às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: joaovitor1-mg
          outputs: dist/snake.svg

      - name: Subir arquivos na branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
